{% set name = "yq" %}
{% set version = "3.4.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ba586a1a6f30cf705b2f92206712df2281cd320280210e7b7b80adcb8f256e3b

build:
  number: 1
  noarch: python
  entry_points:
    - yq=yq:cli
    - xq=yq:xq_cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools_scm
  run:
    - tomlkit >=0.11.6
    - argcomplete >=1.8.1
    - jq
    - python >={{ python_min }}
    - pyyaml >=5.3.1
    - setuptools
    - toml >=0.10.0
    - xmltodict >=0.11.0

test:
  imports:
    - yq
  commands:
    - pip check
    - yq --help
    - xq --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/kislyuk/yq
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Command-line YAML/XML processor - jq wrapper for YAML/XML documents
  doc_url: https://yq.readthedocs.io/en/latest/
  dev_url: https://github.com/kislyuk/yq

extra:
  recipe-maintainers:
    - sodre
    - xhochy
