{% set name = "yq" %}
{% set version = "2.8.1" %}
{% set sha256 = "24d36c7e9e670209562a161b8506ff7e86959be49ba7aee4ca659810801e5710" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    # github.com/sodre/yq:entry_points: replace scripts with entry-points
    #- github_com__sodre__yq__entry_points.patch
    # This patch is needed when running on my MacBook Pro, but not on CircleCI
    #- github_com__sodre__yq__fix-jq-errcode.patch

build:
  number: 0
  noarch: python
  entry_points:
    - yq = yq:main
    - xq = yq:xq_cli
    - tq = yq:tq_cli
  script: 
    - python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - pyyaml >=3.11
    - xmltodict >=0.11.0
    - toml >=0.9.4
    - jq

test:
  requires:
    - pytest
  source_files:
    - test
  imports:
    - yq
  commands:
    - pytest test/test.py
    - yq --help
    - xq --help
    - tq --help
    - test $(cat $RECIPE_DIR/meta.yaml | yq -r .package.name) = 'yq'

about:
  home: https://github.com/kislyuk/yq
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'jq wrapper for YAML and XML documents'

  doc_url: https://yq.readthedocs.io/en/latest/
  dev_url: https://github.com/kislyuk/yq

extra:
  recipe-maintainers:
    - sodre
