schema_version: 1

context:
  name: yq
  version: "4.4.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/b0/70/fe20ba54d325c408ae96e5e08a0f3c399b37f4b6c6d7f14f3c74dc6942b7/yq-${{ version }}.tar.gz
  sha256: bac64df0332bebf05cd6ff2bbd35e421a79bfe29d7c57ee021033a12cd8202cd

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv
  python:
    entry_points:
      - yq=yq:cli
      - xq=yq:xq_cli

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - hatchling
    - hatch-vcs
  run:
    - tomlkit >=0.11.6
    - argcomplete >=1.8.1
    - python >=${{ python_min }}
    - pyyaml >=5.3.1
    - xmltodict >=0.11.0
tests:
  - python:
      python_version:
        - ${{ python_min }}.*
        - '*'
      imports:
        - yq
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - pip check
      - echo '- 1' | yq '.'
      - yq --help
      - xq --help

about:
  license: Apache-2.0
  license_file: LICENSE
  summary: Command-line YAML/XML processor - jq wrapper for YAML/XML documents
  homepage: https://github.com/kislyuk/yq
  repository: https://github.com/kislyuk/yq
  documentation: https://yq.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - sodre
    - xhochy
