schema_version: 1

context:
  name: yq
  version: "4.4.5"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/fd/be/ae37199d28a0a99eb79084f91da94f6e7e58550552361a2397c5032d5d37/yq-${{ version }}.tar.gz
  sha256: e17b21a927d04ae33f61a7284351b69b0a539bfb73b852a04a907b79bcd15de2

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv
  python:
    entry_points:
      - yq=yq:cli
      - xq=yq:xq_cli

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - hatchling
    - hatch-vcs
  run:
    - tomlkit >=0.11.6
    - argcomplete >=1.8.1
    - python >=${{ python_min }}
    - pyyaml >=5.3.1
    - xmltodict >=0.11.0
tests:
  - python:
      python_version:
        - ${{ python_min }}.*
        - '*'
      imports:
        - yq
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - pip check
      - echo '- 1' | yq '.'
      - yq --help
      - xq --help

about:
  license: Apache-2.0
  license_file: LICENSE
  summary: Command-line YAML/XML processor - jq wrapper for YAML/XML documents
  homepage: https://github.com/kislyuk/yq
  repository: https://github.com/kislyuk/yq
  documentation: https://yq.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - sodre
    - xhochy
